### ISSUE TITLE
Can't compile / VS 2015

### ISSUE THREAD

**Issue by anacondama** [CastagnaIT/NFAuthenticationKey#1]
Hey,
I tried to compile the source code but i have several errors in WebSocketHelper.cs. Did i miss something while compiling ? Thanks
`1>------ Build started: Project: NFAuthenticationKey, Configuration: Release Any CPU ------
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(26,17,26,19): error CS1043: { or ; expected
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(26,17,26,19): error CS1513: } expected
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(28,14,28,14): error CS1513: } expected
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(76,13,76,17): error CS1547: Keyword 'void' cannot be used in this context
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(76,34,80,1): error CS1528: Expected ; or = (cannot specify constructor arguments in declaration)
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(76,34,76,35): error CS1003: Syntax error, '[' expected
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(76,62,76,62): error CS1003: Syntax error, '=>' expected
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(79,14,79,14): error CS1003: Syntax error, ']' expected
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(79,14,79,14): error CS1002: ; expected
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(81,13,81,17): error CS1547: Keyword 'void' cannot be used in this context
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(81,43,86,1): error CS1528: Expected ; or = (cannot specify constructor arguments in declaration)
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(81,43,81,44): error CS1003: Syntax error, '[' expected
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(81,86,81,86): error CS1003: Syntax error, '=>' expected
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(85,14,85,14): error CS1003: Syntax error, ']' expected
1>C:\Users\fatim\Desktop\NFAuthenticationKey-048593f06c100583753d7fed80f678fa856c0275\WebSocketHelper.cs(85,14,85,14): error CS1002: ; expected
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by CastagnaIT** [comment]
VS2015 is quite old and could not handle automatically the dependencies
then you have to find a method to manually install them or install a newer version of VS
