### ISSUE TITLE
NFAuthenticationKey.py doesn't work with python 2

### ISSUE THREAD

**Issue by Paco8** [CastagnaIT/NFAuthenticationKey#2]
I tried to use NFAuthenticationKey.py on Linux but it failed to connect to chrome. After trying several things like updating chrome or installing chromium, I realized the problem was actually python 2. When I ran the script with python 3 it worked fine.

This happened on Ubuntu 16.04 but I tried on Ubuntu 20.04 and it happens too.

So I suggest to add a warning stating that the script may not work with python 2.

**Comment by CastagnaIT** [comment]
i have Kubuntu 20.10 with python 2 enviroment and works without problem
you have to find the cause of the problem if in your system not works

**Comment by Paco8** [comment]
It works fine with Python 2 if I remove the _.decode()_ at the end of this line:

`data = urlopen('http://{0}:{1}/json'.format(LOCALHOST_ADDRESS, DEBUG_PORT), timeout=1).read().decode()`

**Comment by CastagnaIT** [comment]
thanks for investigating
i think is not needed also on py3 then can be removed
I think this solves the problem also on MacOS

**Comment by Paco8** [comment]
Actually it fails in Python 3 without the decode() :

```
An error is occurred:
the JSON object must be str, not 'bytes'
```

**Comment by CastagnaIT** [comment]
strange, i just tried with python 3 on Kubuntu and Windows but it works fine...

**Comment by CastagnaIT** [comment]
what python version you have?

**Comment by Paco8** [comment]
This is the version I have in Ubuntu 16.04:
Python 3.5.1+ (default, Mar 30 2016, 22:46:26)

**Comment by CastagnaIT** [comment]
i see docs and yes is right
python 3.5 not support bytes
i have python 3.7 that's why it's ok

**Comment by Paco8** [comment]
Replacing decode() with decode("utf8") seems to work with both Python 2 and 3.

**Comment by CastagnaIT** [comment]
could be if your system default encoding is different need to be specified
actually is the only point where i did not specify it
so it is better cleaner

**Comment by CastagnaIT** [comment]
before publish i will wait a few days to see if i have confirmation to work also on MacOS

**Comment by CastagnaIT** [comment]
has replied works
thanks for helped me
