### ISSUE TITLE
Question regarding implementing Selenium to automatically login to Netflix

### ISSUE THREAD

**Issue by maretodoric** [CastagnaIT/NFAuthenticationKey#4]
Hello,

i do apologize if this is not the correct place to seek assistance, but I've briefly edited NFAuthenticationKey script to include automatic login to netflix using selenium.
I've added:

DELETED

to open_browser and 

DELETED

under operations after br.get(URL)

It worked like a charm (as you can imagine, nfConf is array got from json file containing netflix username and password).
However, today I've noticed that it fails to login, and when trying from python shell (without NFAuthenticationKey script), I've found that netflix issues error message: "Incorrect password. Please try again or you can reset your password."
When i try to do the same in browser, my password is indeed correct.

Can you please let me know if this has anything to do with captcha and do you have any ideas how i can bypass this to make it work?
I've also tried in python shell just running

DELETED

Without clicking the button, when checking page source i can see the correct password is populated for sure. But once the click() is called - Incorrect Password....

**Comment by CastagnaIT** [comment]
Hi netfx website implement a kind of invisible reCAPTCHA v3
you are performing a robot access and this broken the login
maybe by using HTTP2 you will have more chance to pass recaptcha protection but it could still not always work

**please do not publish your code here** your code could be easily used by attackers to steal accesses
we do not assume these responsibilities here, this could lead to a possible lawsuit by the Netfx company

With our script we are already at the limit of legality...
