### ISSUE TITLE
Why am I getting this error??

### ISSUE THREAD

**Issue by drag0nst0ne** [CastagnaIT/NFAuthenticationKey#5]
I copied and pasted EXATCLY how it is and still get this error.

![Captura de Tela (11)](https://user-images.githubusercontent.com/50338430/130335748-862e7735-f01a-4668-962f-4e8e9fb60e05.png)

![Captura de Tela (13)](https://user-images.githubusercontent.com/50338430/130335761-4b9b042b-5f90-4c26-a6c5-f550583a01ad.png)

**Comment by duocodies** [comment]
@drag0nst0ne Use \\ instead of single ( For example c:\\\  )

**Comment by drag0nst0ne** [comment]
New error now

![image](https://user-images.githubusercontent.com/50338430/131840168-a4363eef-6cb6-4426-b6a8-47aa3cdd6653.png)

**Comment by drag0nst0ne** [comment]
Also tried using double quotes, back to previous error
![image](https://user-images.githubusercontent.com/50338430/132022426-e1d47c16-603b-448c-8f3a-bf400ff199e1.png)

**Comment by drag0nst0ne** [comment]
Tried using double quotes, back to previous error
![image](https://user-images.githubusercontent.com/50338430/132022505-ae487c06-9364-4b2c-9a1d-2679cc7c285e.png)

**Comment by CastagnaIT** [comment]
in your second screenshot and also in this last one it is clearly explained how the backslashes must be written
just read...

**Comment by drag0nst0ne** [comment]
I just used Visual Studio to edit the file and it helped me to fix the error, now its working, plus i needed to close the bracket at the end.
